language: cpp
compiler:
 - clang

before_install:
 - ./.travis.helper.sh before_install

install:
 - ./.travis.helper.sh install

before_script:
 - ./.travis.helper.sh before_script

script:
 - ./tests/runner.py build/

os:
 - linux
 - osx
